"""empty message

Revision ID: 1641396f4e7e
Revises: None
Create Date: 2014-08-24 02:28:37.261092

"""

# revision identifiers, used by Alembic.
revision = '1641396f4e7e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
