"""empty message

Revision ID: 25dd6a73424e
Revises: 583f4a33640d
Create Date: 2014-08-23 23:17:41.898652

"""

# revision identifiers, used by Alembic.
revision = '25dd6a73424e'
down_revision = '583f4a33640d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('description', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
