"""empty message

Revision ID: 36d09459e16d
Revises: 506b3b95e1af
Create Date: 2014-08-24 03:47:22.188942

"""

# revision identifiers, used by Alembic.
revision = '36d09459e16d'
down_revision = '506b3b95e1af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone_offset', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone_offset')
    ### end Alembic commands ###
