"""empty message

Revision ID: 3c3c09e5fcd9
Revises: 25dd6a73424e
Create Date: 2014-08-24 00:47:58.220651

"""

# revision identifiers, used by Alembic.
revision = '3c3c09e5fcd9'
down_revision = '25dd6a73424e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
