"""empty message

Revision ID: 4118f13708a8
Revises: 1641396f4e7e
Create Date: 2014-08-24 02:29:30.659300

"""

# revision identifiers, used by Alembic.
revision = '4118f13708a8'
down_revision = '1641396f4e7e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
