"""empty message

Revision ID: 42b644a73f26
Revises: 36d09459e16d
Create Date: 2014-08-24 04:06:34.251309

"""

# revision identifiers, used by Alembic.
revision = '42b644a73f26'
down_revision = '36d09459e16d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
