"""empty message

Revision ID: 583f4a33640d
Revises: 1929550bddee
Create Date: 2014-08-23 22:21:48.686359

"""

# revision identifiers, used by Alembic.
revision = '583f4a33640d'
down_revision = '1929550bddee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
