"""empty message

Revision ID: 950f68dbab0
Revises: 4118f13708a8
Create Date: 2014-08-24 02:31:05.689243

"""

# revision identifiers, used by Alembic.
revision = '950f68dbab0'
down_revision = '4118f13708a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('category', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'category')
    ### end Alembic commands ###
